### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by EddieOne** [bcoin-org/bcoin-zmq#1]
Maybe there is a plugin directory?

**Comment by bucko13** [comment]
`npm install —save bzmq` and then use the plugin interface on the bcoin node as in this example: https://github.com/bcoin-org/bcoin/blob/master/docs/Examples/peers-plugin.js

**Comment by EddieOne** [comment]
Hi @bucko13 How do I start this with `bcoin/bin/node`? I get `unknown option '--plugins'`. Can I add `zmq-pub-hashblock` to the config?

**Comment by bucko13** [comment]
The Readme for this repo shows the command for starting bcoin with plugins. If you're getting `plugins` as an unknown option than you might be on an old version of bcoin. plugins can also be added via your own script as in the bcoin node binary. It's not available via config (see config docs [here](https://github.com/bcoin-org/bcoin/blob/master/docs/Configuration.md)). See bcoin node binary with mounted wallet plugin [here](https://github.com/bcoin-org/bcoin/blob/master/bin/node).
